# Generated by Django 2.2.4 on 2022-01-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='apl',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='latl',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
